### ISSUE TITLE
How to treat the "use" column when publishing

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#15]
@dirkmaes33 the column `use` in the distributions spreadsheet has:

- `n` (523)
- `y` (7226)
- empty (289)

How should these be treated? I assume that column just indicates if they should be included for analysis, and that _all_ can be published as part of the checklist?

**Comment by dirkmaes33** [comment]
That is only for analysis reasons ... and it would be best not to show the records marked with "n". You would end up with a lot of very strange species in the database that were only seen once in a region and usually because somebody put them there ... But, they appear in the local publications, so if you want to publish them, please cite the correct references!
The species with an empty column here are the ones from the individual Macaronesian archipelagos. For analysis, I just used a species' presence in the archipelago as a whole (3 possible regions) and not on every single island. I would publish the species for the individual archipelagos on a seperate sheet (as is done) and only keep the archipelago presence in the European sheet (if that is clear ...?).

**Comment by peterdesmet** [comment]
> But, they appear in the local publications, so if you want to publish them, please cite the correct references!

They will have the same references as the other species for that country, so `Aglais io` in `IS` (indicated with n) will have `Erling Ólafsson (pers. comm.) | Ole Karsholt (pers. comm.)`. If that is OK, I would include them. One option would be to overwrite their `occurrenceStatus` to `excluded`?

**Comment by dirkmaes33** [comment]
again, GBIF should be changed and not the status of the species ... A. io is a vagrant in Iceland and gets there every now and then. So "absent" is not correct because it shows up every odd year, and present is also not correct because it is not present all the time ...  Please do mention to GBIF that there are more categories needed to give a correct representation of a species status in a region!

**Comment by peterdesmet** [comment]
@dirkmaes33 see #18 for status issue. Here I just want to confirm you are ok with:

> But, they appear in the local publications, so if you want to publish them, please cite the correct references!

Given that the reference would be the same reference as all species for that country.

**Comment by dirkmaes33** [comment]
yes, ok with me
